# .travis.yml
sudo: false
language: cpp
git:
  depth : 1
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    sources: ['kalakris-cmake', 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
    packages: ['cmake', 'g++-4.8', 'clang-3.7']
before_install:
  - if [ $TRAVIS_OS_NAME == linux ] && [ $CC  == gcc ]; then export VMF_GCOV_OPTS='-DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON'; fi
  - if [ "$VMF_GCOV_OPTS" != "" ]; then pip install --user cpp-coveralls; fi
  - if [ "$VMF_GCOV_OPTS" != "" ]; then pip install --user codecov; fi
before_script:
  - mkdir ../build
  - cd ../build
script:
  - if [ $TRAVIS_OS_NAME == linux ] && [ $CC  == gcc     ]; then export CC=gcc-4.8;      fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $CC  == clang   ]; then export CC=clang-3.7;    fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $CXX == g++     ]; then export CXX=g++-4.8;     fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $CXX == clang++ ]; then export CXX=clang++-3.7; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then ldd --version; fi
  - if [[ $CC  == gcc*  ]]; then VMF_SHARED=ON; else VMF_SHARED=OFF; fi
  - cmake -DBUILD_TESTS=ON -DBUILD_SAMPLES=ON -DBUILD_SHARED_LIBS=$VMF_SHARED $VMF_GCOV_OPTS ../vmf
  - make
  - cd ./bin/
  - ./unit-tests
  - ./unit-tests-ds
  - if [ $TRAVIS_OS_NAME == osx ] && [ $CC  == clang ]; then cd ..; mkdir ios; cd ios; python ../../vmf/platforms/ios/build_ios_framework.py $(pwd); fi
after_success:
  - if [ "$VMF_GCOV_OPTS" != "" ]; then coveralls --exclude build/CMakeFiles --exclude vmf/3rdparty --exclude vmf/modules/vmfcore/test --exclude vmf/modules/vmdatasource/test --gcov-options '\-lp' --gcov gcov-4.8 --root ../.. --build-root ..; fi
  - if [ "$VMF_GCOV_OPTS" != "" ]; then codecov --root ../.. --gcov-exec gcov-4.8; fi
notifications:
  email: false
  webhooks: https://coveralls.io/webhook?repo_token=kXDrxzQdBiK3aEgUSlsbL3IVMP0Mvr4oH


